name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Determine current version
        id: versioning
        run: echo "::set-output name=version::${{ github.run_id }}"

      - name: Build and publish
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            dotnet publish -r win-x64 -c Release --self-contained true -p:PublishSingleFile=true ./ContentFinder/ContentFinder.csproj
          else
            dotnet publish -r linux-x64 -c Release --self-contained true -p:PublishSingleFile=true ./ContentFinder/ContentFinder.csproj
          fi

      - name: Determine file extension
        shell: bash
        id: file-extension
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            echo "::set-output name=extension::exe"
          else
            echo "::set-output name=extension::"
          fi

      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: ContentFinder
          path: |
            ./ContentFinder/bin/Release/net8.0/
            ${{ matrix.os }}-x64/
            publish/ContentFinder${{ steps.file-extension.outputs.extension }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download release artifact
        uses: actions/download-artifact@v2
        with:
          name: ContentFinder

      - name: GitHub Publish - Release
        uses: softprops/action-gh-release@v1      
        with:
          tag_name: ${{ github.workflow }}
          name: Release v${{ github.run_number }}
          draft: false
          prerelease: true
          files:
            ContentFinder${{ steps.file-extension.outputs.extension }}
